# ModernZ configuration
# Sleek modern OSC tuned for a high-Hz RTX 4050 setup.
layout=default
icon_theme=fluent
icon_style=outline
font=mpv-osd-symbols
window_top_bar=auto
show_window_title=no
window_controls=yes
windowcontrols_independent=yes
show_title=yes
title=${media-title}
title_font_size=24
show_chapter_title=yes
showonpause=yes
keeponpause=no
hidetimeout=1500
fadeduration=200
fadein=yes
sub_margins=yes
dynamic_margins=yes
subtitles_button=yes
audio_tracks_button=yes
jump_buttons=yes
jump_amount=10
jump_more_amount=60
track_nextprev_buttons=yes
volume_control=yes
playlist_button=yes
fullscreen_button=yes
info_button=yes
ontop_button=yes
screenshot_button=yes
download_button=yes
loop_button=yes
shuffle_button=no
speed_button=yes
seekbar_height=medium
seekrange=yes
seekbarkeyframes=yes
automatickeyframemode=yes
persistent_progress=no
tooltip_hints=yes
hover_effect=size,glow,color,box
button_hover_size=115
osc_color=#000000
seekbarfg_color=#FF8232
seekbarbg_color=#777777
seek_handle_color=#FF8232
nibbles_style=gap
